## Calculation of column density of CO(3-2) using the information given for C$^{18}$O (1-0) transition


The equation to be used to calculate the N$_{tot}$ is given by:
$N_{tot} = \frac{3k}{8\pi^3\nu S\mu^2R_i}\frac{Q_{rot}}{g_j g_k g_I} exp \left(\frac{E_u}{kT_{ex}}\right)$


In [1]:
import numpy as np
import math
import pandas as pd


idx,area_ellipse,area_exact,temp,major_sigma,minor_sigma,position_angle,radius,v_centre,sigma_v,x_centre,y_centre = np.loadtxt(
    '../tables/integrated_temperature_catalogue.csv', delimiter = ",",skiprows = 1,unpack = True)


def N(f_1,f_2,t,t_ex,h_to_co,co_to_13co,E_u):
    '''
    this function is to calculate the column density. The excitation temperature will be taken 30 and 20 K for two 
    different cases while t is the integrated temperature taken from the csv file. A factor of 10000 is
    because we are trying to get the column density of a hydrogen molecule.
    '''
    return (f_1)*(t_ex+f_2)*np.exp(E_u/t_ex)*t*1e+5*h_to_co*co_to_13co

B,J,factor_1,factor_2 = np.loadtxt('../../../../parameters_of_different_molecules/Factors_for_CO_molecule - Sheet1.csv',delimiter=",",
                    skiprows = 1, usecols = (1,4,5,6),unpack=True)


#only for 13CO(2-1)
E_co = B[2]*J[2]*(J[2]+1)
E_co = E_co*4.799635701275045e-11 # hertz to kelvin conversion


column_density_30 = []
column_density_20 = []


for i in range(len(temp)):
    column_density_30.append(N(f_1 = factor_1[2],f_2 = factor_2[2],t = temp[i],t_ex = 30, h_to_co=1e+4,co_to_13co=60,E_u = E_co))
    column_density_20.append(N(f_1 = factor_1[2],f_2 = factor_2[2],t = temp[i],t_ex = 20, h_to_co=1e+4,co_to_13co=60,E_u = E_co))



def m(n):
    '''
    the mass of the clump using its column density. We need to take into account a factor of 10^4
    when we use CO:H_2 and then use it to find the mass. The solid angle used is for the beam which is
    15". One needs to use this beam size to find the Gaussian area which will ultimately give the \omega
    '''
    mu = 2.8
    m_h = 2*1.67e-24
    d = 3*3.1e+21
    theta = 15
    deg_to_rad = np.pi/180
    theta_rad = 15/3600*deg_to_rad
    factor = np.sqrt(2*math.log(2))
    omega = theta_rad**2/factor
    gram_to_solar_mass =5.02805654165827162e-34
    return mu*m_h*d**2*omega*n*gram_to_solar_mass


mass_30 = []
mass_20 = []

for i in range(len(temp)):
    mass_30.append(m(column_density_30[i]))
    mass_20.append(m(column_density_20[i]))


    
    
# Making a csv table

add_20 = {'column_density':column_density_20,'mass':mass_20}
add_30 = {'column_density':column_density_30,'mass':mass_30}



Final_20 = pd.DataFrame(add_20)
Final_30 = pd.DataFrame(add_30)

Final_20

column_density          mass
0     1.272437e+25  23244.023505
1     1.052712e+25  19230.241820
2     8.719950e+24  15929.020345
3     8.269831e+24  15106.772703
4     7.388058e+24  13496.008470
5     8.491215e+24  15511.182417
6     4.207799e+24   7686.524694
7     4.462806e+24   8152.354222
8     4.046964e+24   7392.722465
9     4.814932e+24   8795.595755
10    2.764471e+24   5049.950654
11    1.029845e+24   1881.252503
12    7.948947e+23   1452.060348
13    1.190477e+23    217.468303
14    5.369778e+22     98.091509
15    1.868154e+23    341.261872
16    2.489990e+22     45.485467
17    1.967174e+23    359.350076
18    9.999402e+22    182.662378
19    1.671576e+23    305.352223
20    1.014674e+24   1853.537613
21    3.042854e+23    555.848147
22    3.482477e+22     63.615549
23    9.852376e+22    179.976605
24    1.493963e+23    272.907067
25    8.210467e+22    149.983312
26    2.101344e+22     38.385939
27    1.793568e+23    327.637014
28    1.531740e+23    279.808043
29    2.862045e+23    522.819126
30    3.662223e+23    668.990331
31    1.286332e+23    234.978538
32    5.763884e+22    105.290765
33    3.187591e+22     58.228768
34    4.896640e+22     89.448547
35    8.029934e+22    146.685460

In [2]:
Final_30

column_density          mass
0     1.444498e+25  26387.116727
1     1.195062e+25  21830.585203
2     9.899075e+24  18082.967396
3     9.388090e+24  17149.534141
4     8.387082e+24  15320.959848
5     9.639410e+24  17608.628769
6     4.776784e+24   8725.908588
7     5.066273e+24   9254.728313
8     4.594201e+24   8392.377962
9     5.466015e+24   9984.949972
10    3.138287e+24   5732.812881
11    1.169103e+24   2135.638409
12    9.023816e+23   1648.410220
13    1.351455e+23    246.874707
14    6.095888e+22    111.355597
15    2.120769e+23    387.407836
16    2.826690e+22     51.636083
17    2.233178e+23    407.941955
18    1.135154e+23    207.362271
19    1.897609e+23    346.642428
20    1.151879e+24   2104.175869
21    3.454313e+23    631.010803
22    3.953383e+22     72.217743
23    1.118463e+23    204.313324
24    1.695978e+23    309.809987
25    9.320699e+22    170.264290
26    2.385491e+22     43.576546
27    2.036097e+23    371.940603
28    1.738865e+23    317.644124
29    3.249055e+23    593.515546
30    4.157434e+23    759.452250
31    1.460272e+23    266.752704
32    6.543285e+22    119.528346
33    3.618622e+22     66.102554
34    5.558772e+22    101.543920
35    9.115755e+22    166.520498

In [3]:
Final_20.to_csv('../tables/column_20.csv')
Final_30.to_csv('../tables/column_30.csv')

### Calculating Virial parameters

In [5]:
import numpy as np
import math
import pandas as pd



radius_pc = 3000*radius*np.pi/(180*3600)
mass_20 = np.loadtxt('../tables/column_20.csv',delimiter = ",",skiprows =1,usecols=(2,),unpack= True)
mass_30 = np.loadtxt('../tables/column_30.csv',delimiter = ",",skiprows =1,usecols=(2,),unpack= True)


def virial_para(v,r,m):
    return 1.2*v**2*r*1000/m


virial_para_30 = []
virial_para_20 = []

for i in range(len(radius)):
    virial_para_30.append(virial_para(sigma_v[i],radius_pc[i],mass_30[i]))
    virial_para_20.append(virial_para(sigma_v[i],radius_pc[i],mass_20[i]))

virial_para_30

[0.23753139575001264,
 0.24773703874616756,
 0.21212665193701385,
 0.20413623473197004,
 0.164478405353745,
 0.2074739873363024,
 0.1684091925686823,
 0.1747650573623351,
 0.17109542915480547,
 0.17040105440182962,
 0.16709662780480317,
 0.060718437926055954,
 0.19532798859227224,
 0.051843912273207525,
 0.0748397060115704,
 0.10587985548861724,
 0.0,
 0.29790229361402004,
 0.053032088071625225,
 0.04368259263873998,
 0.2276220718908772,
 0.09698131619958214,
 0.0,
 0.03961432334472026,
 0.1862522866611048,
 0.059037322209453034,
 0.0,
 0.04800599365636976,
 0.04404657559038481,
 0.06072957672058621,
 0.03315800467849113,
 0.04851720604995035,
 0.08141785486602347,
 0.11826934391964734,
 0.06446249768609284,
 0.0]

In [7]:
final_catalogue = {'RA(deg)':x_centre,'DEC (deg)':y_centre,'Integrated temperature (K km/s)':temp,
                   'Mass (Tex = 20)(M_sun)':mass_20,'Mass (Tex = 30)(M_sun)':mass_30,
                   'Virial parameter (Tex = 20)':virial_para_20,'Virial parameter (Tex = 30)':virial_para_30,
                   'column density (Tex = 20)':column_density_20,
                   'column density (Tex = 30)':column_density_30,
                   'area_ellipse(arcsec)':area_ellipse,'area_exact(arcsec)':area_exact,
                   'semi_major(arcsec)':major_sigma,'minor_sigma(arcsec)':minor_sigma,
                   'central velocity (km/s)':v_centre/1000,
                   'v_rms (km/s)':sigma_v,
                   'position angle (in deg)':position_angle,
                   'effective radius (arcsec)':radius}

final_catalogue = pd.DataFrame(final_catalogue)

In [8]:
final_catalogue

RA(deg)  DEC (deg)  Integrated temperature (K km/s)  \
0   270.206349 -23.353319                      3674.894407   
1   270.205828 -23.353202                      3040.313055   
2   270.206813 -23.355070                      2518.387910   
3   270.206615 -23.355356                      2388.390052   
4   270.206019 -23.356079                      2133.727237   
5   270.206805 -23.355247                      2452.327477   
6   270.204820 -23.359430                      1215.244280   
7   270.204946 -23.358982                      1288.892215   
8   270.204796 -23.359185                      1168.793967   
9   270.205344 -23.358297                      1390.589097   
10  270.203969 -23.358605                       798.400303   
11  270.201333 -23.352825                       297.427177   
12  270.244414 -23.307477                       229.571634   
13  270.248799 -23.306274                        34.381872   
14  270.182986 -23.318930                        15.508328   
15  270.225237 -23.393765                        53.953712   
16  270.204777 -23.380888                         7.191280   
17  270.218119 -23.306448                        56.813468   
18  270.212752 -23.333094                        28.879034   
19  270.247833 -23.306926                        48.276374   
20  270.238897 -23.307258                       293.045436   
21  270.209204 -23.368323                        87.879934   
22  270.210821 -23.373188                        10.057657   
23  270.207541 -23.366960                        28.454412   
24  270.199485 -23.325793                        43.146775   
25  270.208255 -23.338584                        23.712454   
26  270.218886 -23.361378                         6.068841   
27  270.200332 -23.390662                        51.799613   
28  270.174920 -23.363522                        44.237824   
29  270.216269 -23.346082                        82.658025   
30  270.184608 -23.327472                       105.767783   
31  270.190198 -23.323063                        37.150251   
32  270.157849 -23.362789                        16.646535   
33  270.232421 -23.356220                         9.206004   
34  270.192355 -23.345168                        14.141870   
35  270.175667 -23.332001                        23.191061   

    Mass (Tex = 20)(M_sun)  Mass (Tex = 30)(M_sun)  \
0             23244.023505            26387.116727   
1             19230.241820            21830.585203   
2             15929.020345            18082.967396   
3             15106.772703            17149.534141   
4             13496.008470            15320.959848   
5             15511.182417            17608.628769   
6              7686.524694             8725.908588   
7              8152.354222             9254.728313   
8              7392.722465             8392.377962   
9              8795.595755             9984.949972   
10             5049.950654             5732.812881   
11             1881.252503             2135.638409   
12             1452.060348             1648.410220   
13              217.468303              246.874707   
14               98.091509              111.355597   
15              341.261872              387.407836   
16               45.485467               51.636083   
17              359.350076              407.941955   
18              182.662378              207.362271   
19              305.352223              346.642428   
20             1853.537613             2104.175869   
21              555.848147              631.010803   
22               63.615549               72.217743   
23              179.976605              204.313324   
24              272.907067              309.809987   
25              149.983312              170.264290   
26               38.385939               43.576546   
27              327.637014              371.940603   
28              279.808043              317.644124   
29              522.819126              593.515546   
30              668.990331            

In [10]:
final_catalogue.to_csv('../tables/final_catalogue_13co.csv')

In [20]:
mass_20 = np.loadtxt('../table/temperature_of_clumps_t_ex_20 - Sheet1-2.csv',delimiter = ",", skiprows = 1,usecols=(12,),unpack = True)
mass_30 = np.loadtxt('../table/temperature_clumps_tex_30 - Sheet1-2.csv',delimiter = ",", skiprows = 1,usecols=(12,),unpack = True)
mass_lum = np.loadtxt('../table/table.csv',delimiter = ",", skiprows = 1,usecols=(2,),unpack = True)


def gamma(m_1,m_2):
    '''
    gamma = virial parameter
    m_1 = virial mass
    m_2 = luminous mass
    '''
    return 1.12*m_1/m_2

virial_para_20 = []
virial_para_30 = []

for i in range(len(mass_lum)):
    virial_para_20.append(gamma(mass_20[i],mass_lum[i]))
    virial_para_30.append(gamma(mass_30[i],mass_lum[i]))
    
    


In [22]:
virial_para_30

[0.08226330284180612,
 0.08234980833266888,
 0.08223723481068616,
 0.0822253364993973,
 0.08204571086158124,
 0.08224108834361805,
 0.08227163432074877,
 0.08223301214282398,
 0.08236267239114205,
 0.08226740389070318,
 0.08250800414745602,
 0.08211785445659073,
 0.08228459455138797,
 0.08232842422185536,
 0.08235363110183452]

In [21]:
# Making a csv table

gamma_table = {'virial_para_20':virial_para_20,'virial_para_30':virial_para_30}



Final = pd.DataFrame(gamma_table)

Final.to_csv('../table/gamma_table.csv')

In [26]:
import numpy as np
import math
import pandas as pd


radius_arcsec, sigma_v,mass = np.loadtxt('../table/temperature_clumps_tex_30 - Sheet1.csv',delimiter = ",",skiprows = 1,
                                        usecols = (6,8,12),unpack = True)

radius_pc = 3000*radius_arcsec*np.pi/(180*3600)

def virial_para(v,r,m):
    return 1.2*v**2*r*1000/m


virial_para_30 = []

for i in range(len(radius)):
    virial_para_30.append(virial_para(sigma_v[i],radius_pc[i],mass[i]))

virial_para_30

[9.37723091944221,
 13.491614170084437,
 10.610603063243518,
 22.086702652284604,
 26.119522889831295,
 4.753436692862013,
 0.0,
 5.872255981983686,
 4.8971232463920815,
 3.3283798533266804,
 4.489065494621934,
 2.54026395312161,
 0.0,
 0.0,
 0.0]

In [32]:
Final = pd.DataFrame(virial_para_30)

Final.to_csv('../table/virial_para_30.csv')

In [28]:
radius_arcsec

array([6.66868941, 1.80164292, 2.53567366, 2.96672345, 1.85202274,
       3.44072012, 1.75225716, 2.00448734, 1.83055039, 4.84683898,
       2.20722141, 3.04056085, 0.        , 0.        , 1.31431067])

In [29]:
sigma_v

array([1.88921002, 0.99123506, 1.46076271, 1.36060822, 1.11190196,
       0.45452812, 0.        , 0.45066604, 0.42528689, 0.42957093,
       0.39367892, 0.32891078, 0.        , 0.        , 0.        ])

In [31]:
mass

array([44.3  ,  2.29 ,  8.9  ,  4.34 ,  1.53 ,  2.61 ,  0.691,  1.21 ,
        1.18 ,  4.69 ,  1.33 ,  2.26 ,  0.305,  0.309,  0.437])